import {
  isMarshalClassObject,
  isMarshalDataObject,
  isMarshalExtendableObject,
  isMarshalHash,
  isMarshalMarshalObject,
  isMarshalModuleObject,
  isMarshalModuleOrClassObject,
  isMarshalStandardObject,
  isMarshalStructObject,
  isMarshalUserObject,
} from './typeGuards';

describe('typeGuards', () => {
  const objectDictionary = {
    string: 'Test string',
    array: [],
    null: null,
    true: true,
    false: false,
    float: 0.5,
    bigNum: BigInt(1),
    regexp: /test/,
    symbol: Symbol.for('a'),
    class: { __class: 'Class', name: 'Object' },
    module: { __class: 'Module', name: 'Kernel' },
    classOrModule: { __class: 'ModuleOrClass', name: 'Kernel' },
    basicHash: { __class: 'Hash', [Symbol.for('a')]: 0, b: 1 },
    hashWithDefault: {
      __class: 'Hash',
      __default: 55,
      [Symbol.for('a')]: 0,
      b: 1,
    },
    extendedHash: {
      __class: 'Hash',
      [Symbol.for('a')]: 0,
      __extendedModules: [
        {
          __class: 'Module',
          name: 'Extension',
        },
      ],
    },
    standardObject: {
      __class: Symbol.for('PointObject'),
      '@x': 4,
      '@y': 5,
    },
    extendedObject: {
      __class: Symbol.for('PointObject'),
      __extendedModules: [
        { __class: 'Module', name: 'PrettyPrinter' },
        { __class: 'Module', name: 'Point3D' },
      ],
      '@x': 0,
      '@y': 0,
      '@z': 1,
    },
    marshalObject: {
      __class: Symbol.for('MarshalDump'),
      __marshal_load: 'Some Data',
    },
    dataObject: {
      __class: Symbol.for('DataDump'),
      __load_data: 'Some Data',
    },
    dumpObject: {
      __class: Symbol.for('DataObject'),
      __load: Buffer.from('SomeBinaryData', 'utf8'),
    },
    basicStruct: {
      __class: Symbol.for('PointStruct'),
      __type: 'Struct',
      x: 1,
      y: 2,
    },
    extendedStruct: {
      __class: Symbol.for('PointStruct'),
      __type: 'Struct',
      x: 0,
      y: 1,
      '@z': 5,
      __extendedModules: [
        {
          __class: 'Module',
          name: 'Extension',
        },
      ],
    },
  };

  const testTypeGuard = (typeGuard: (object: unknown) => boolean, expectations: Record<keyof typeof objectDictionary, boolean>) => {
    it(`guards type properly in ${typeGuard.name}`, () => {
      expect(Object.fromEntries(Object.entries(objectDictionary).map(([key, value]) => [key, typeGuard(value)]))).toEqual(expectations);
    });
  };

  testTypeGuard(isMarshalExtendableObject, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: false,
    module: false,
    classOrModule: false,
    basicHash: true,
    hashWithDefault: true,
    extendedHash: true,
    standardObject: true,
    extendedObject: true,
    marshalObject: false,
    dataObject: false,
    dumpObject: false,
    basicStruct: true,
    extendedStruct: true,
  });

  testTypeGuard(isMarshalClassObject, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: true,
    module: false,
    classOrModule: false,
    basicHash: false,
    hashWithDefault: false,
    extendedHash: false,
    standardObject: false,
    extendedObject: false,
    marshalObject: false,
    dataObject: false,
    dumpObject: false,
    basicStruct: false,
    extendedStruct: false,
  });

  testTypeGuard(isMarshalModuleObject, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: false,
    module: true,
    classOrModule: false,
    basicHash: false,
    hashWithDefault: false,
    extendedHash: false,
    standardObject: false,
    extendedObject: false,
    marshalObject: false,
    dataObject: false,
    dumpObject: false,
    basicStruct: false,
    extendedStruct: false,
  });

  testTypeGuard(isMarshalModuleOrClassObject, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: false,
    module: false,
    classOrModule: true,
    basicHash: false,
    hashWithDefault: false,
    extendedHash: false,
    standardObject: false,
    extendedObject: false,
    marshalObject: false,
    dataObject: false,
    dumpObject: false,
    basicStruct: false,
    extendedStruct: false,
  });

  testTypeGuard(isMarshalHash, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: false,
    module: false,
    classOrModule: false,
    basicHash: true,
    hashWithDefault: true,
    extendedHash: true,
    standardObject: false,
    extendedObject: false,
    marshalObject: false,
    dataObject: false,
    dumpObject: false,
    basicStruct: false,
    extendedStruct: false,
  });

  testTypeGuard(isMarshalStandardObject, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: false,
    module: false,
    classOrModule: false,
    basicHash: false,
    hashWithDefault: false,
    extendedHash: false,
    standardObject: true,
    extendedObject: true,
    marshalObject: false,
    dataObject: false,
    dumpObject: false,
    basicStruct: false,
    extendedStruct: false,
  });

  testTypeGuard(isMarshalMarshalObject, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: false,
    module: false,
    classOrModule: false,
    basicHash: false,
    hashWithDefault: false,
    extendedHash: false,
    standardObject: false,
    extendedObject: false,
    marshalObject: true,
    dataObject: false,
    dumpObject: false,
    basicStruct: false,
    extendedStruct: false,
  });

  testTypeGuard(isMarshalUserObject, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: false,
    module: false,
    classOrModule: false,
    basicHash: false,
    hashWithDefault: false,
    extendedHash: false,
    standardObject: false,
    extendedObject: false,
    marshalObject: false,
    dataObject: false,
    dumpObject: true,
    basicStruct: false,
    extendedStruct: false,
  });

  testTypeGuard(isMarshalDataObject, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: false,
    module: false,
    classOrModule: false,
    basicHash: false,
    hashWithDefault: false,
    extendedHash: false,
    standardObject: false,
    extendedObject: false,
    marshalObject: false,
    dataObject: true,
    dumpObject: false,
    basicStruct: false,
    extendedStruct: false,
  });

  testTypeGuard(isMarshalStructObject, {
    string: false,
    symbol: false,
    array: false,
    null: false,
    true: false,
    false: false,
    float: false,
    bigNum: false,
    regexp: false,
    class: false,
    module: false,
    classOrModule: false,
    basicHash: false,
    hashWithDefault: false,
    extendedHash: false,
    standardObject: false,
    extendedObject: false,
    marshalObject: false,
    dataObject: false,
    dumpObject: false,
    basicStruct: true,
    extendedStruct: true,
  });
});
